### ISSUE TITLE
Error on Search on belongs_to with class_name option

### ISSUE THREAD

**Issue by sobanakram** [thoughtbot/administrate#1179]
Error:
![screenshot from 2018-06-19 17-58-41](https://user-images.githubusercontent.com/10559510/41598769-a67b80b0-73ea-11e8-89a5-21ce1b48f289.png)

Dashboard:

```ruby
ATTRIBUTE_TYPES = {
  sender: Field::BelongsTo.with_options(
    class_name: "User",
    searchable: true,
    searchable_field: :phone_number,
  )
}
```

Model:

```ruby
belongs_to :sender, class_name: 'User', foreign_key: :sender_id
```

**Comment by andrepcg** [comment]
Having the same issue.

```
ATTRIBUTE_TYPES = {
    owner: Field::BelongsTo.with_options(class_name: 'Person', searchable: true, searchable_field: :first_name),
}
```

`PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "owners"
LINE 1: ...name" AS CHAR(256))) LIKE '%simão%' OR LOWER(CAST("owners".."first_name"`

It's trying to use the `owners` table but I set the class to be `Person` so it should use `people.first_name` in the query

Rails 5.1.7
Administrate 0.11.0

**Comment by andrepcg** [comment]
It might be fixed in https://github.com/thoughtbot/administrate/pull/1264

**Comment by bjgaynor** [comment]
This is still not working to the best of my knowledge and it's a shame because I have a lot of custom class names that now can't be searchable.

**Comment by ksearfos** [comment]
Agreed -- I am still having this issue

**Comment by pablobm** [comment]
Should be fixed now. Please let us know if not.

**Comment by andrepcg** [comment]
@pablobm Still having the same issue on v0.13.

https://github.com/thoughtbot/administrate/issues/1179#issuecomment-522488557

It still tries searching in the table named `owners` instead of `people`

**Comment by sedubois** [comment]
@andrepcg release 0.13.0 was on March 13 but that PR was merged on March 21. Could you try master?
