### ISSUE TITLE
Installing Administrate on an existing project

### ISSUE THREAD

**Issue by edwinwills** [thoughtbot/administrate#1614]
* What were you trying to do?
I added the gem to an existing project, and tried to run `rails generate administrate:install`.

* What did you end up with (logs, or, even better, example apps are great!)?
```ruby
/administrate/lib/generators/administrate/dashboard/dashboard_generator.rb:119:in `const_get': uninitialized constant Page (NameError)
```

I took a dig around the code, and it looks like Administrate is trying to work out which models to generate dashboards for by searching the routes file, and trying to initialise classes based on the names in the routes file.

In my case, I have a controller/route for `pages`, but no model backing it (as these are just static pages the site serves).

The method that was causing the issues for me is `run_dashboard_generators`, and I was able to fix it by monkey patching the method as below:

```ruby
def run_dashboard_generators
  singular_dashboard_resources.each do |resource|
    begin
      call_generator "administrate:dashboard", resource,
         "--namespace", namespace
    rescue NameError
    end
  end
end
```

Not sure if this is something you'd like in the gem, but happy to create a PR along the lines of my monkey patch if that's useful.

* What versions are you running?
  - Rails 6.0.2.2
  - administrate 0.13.0

**Comment by sedubois** [comment]
Is this fixed by https://github.com/dmitry-solomadin/administrate/commit/b13a1f860c5a800cd4f45d6e9dc376af1e20e25c? Maybe it’s not yet in the version you are running?

**Comment by edwinwills** [comment]
Ah interesting - this was merged a while ago, but doesn't seem to solve my problem. I also tried to just comment out the existing `admin` namespace in my routes file, but ended up getting `Could not find generator 'administrate:routes'. Maybe you meant "administrate:views"?` when I tried to install again.

**Comment by sedubois** [comment]
Sorry I gave the wrong link (was browsing from the GitHub app which isn't the most helpful). I meant this PR:
https://github.com/thoughtbot/administrate/pull/1579

It's only available on Administrate master (not the latest 0.13.0), are you running with it?

**Comment by edwinwills** [comment]
Ah yes, that fixed it. Pulled against master and killed spring and the install ran fine. Thanks for your help.
