### ISSUE TITLE
After running install generator I get this error `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by warrenbrown** [thoughtbot/administrate#308]

**Comment by mhelmetag** [comment]
Can you possibly post the stacktrace? That should help with debugging...

**Comment by brigneld** [comment]
create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_manifest.rb
       route  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
      create  app/dashboards/role_dashboard.rb
      create  app/controllers/admin/roles_controller.rb
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
      create  app/dashboards/address_dashboard.rb
      create  app/controllers/admin/addresses_controller.rb
      create  app/dashboards/child_dashboard.rb
/home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:661:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:871:in `derive_class_name'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:147:in `class_name'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:92:in `relationship_options_string'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:79:in `association_type'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:55:in `redundant_attributes_for'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:50:in `block in redundant_attributes'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `flat_map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `redundant_attributes'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:41:in `attributes'
	from (erb):11:in `template'
	from /home/damien/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /home/damien/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:26:in `block in template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:25:in `template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:28:in `create_dashboard_definition'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by brigneld** [comment]
I also have this problem. Here is the stack trace: 
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_manifest.rb
       route  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
      create  app/dashboards/role_dashboard.rb
      create  app/controllers/admin/roles_controller.rb
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
      create  app/dashboards/address_dashboard.rb
      create  app/controllers/admin/addresses_controller.rb
      create  app/dashboards/child_dashboard.rb
/home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:661:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:871:in `derive_class_name'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/reflection.rb:147:in `class_name'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:92:in `relationship_options_string'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:79:in `association_type'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:55:in `redundant_attributes_for'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:50:in `block in redundant_attributes'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `flat_map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `redundant_attributes'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:41:in `attributes'
	from (erb):11:in `template'
	from /home/damien/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /home/damien/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:26:in `block in template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators/named_base.rb:25:in `template'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:28:in `create_dashboard_definition'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:29:in `block in run_dashboard_generators'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/administrate-0.1.2/lib/generators/administrate/install/install_generator.rb:28:in `run_dashboard_generators'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/generators.rb:157:in `invoke'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/damien/.rvm/gems/ruby-2.2.2/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by johncblandii** [comment]
Same thing here:

```
/Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:661:in `source_reflection': undefined method `klass' for nil:NilClass (NoMethodError)
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:871:in `derive_class_name'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/reflection.rb:147:in `class_name'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `relationship_options_string'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:94:in `association_type'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:57:in `redundant_attributes_for'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:52:in `block in redundant_attributes'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:51:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:51:in `flat_map'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:51:in `redundant_attributes'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:43:in `attributes'
	from (erb):11:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:46:in `identical?'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:72:in `on_conflict_behavior'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:113:in `invoke_with_conflict_check'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/install/install_generator.rb:31:in `block in run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/install/install_generator.rb:30:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/administrate-4eede3b15df6/lib/generators/administrate/install/install_generator.rb:30:in `run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/johncblandii/Work/katapultmedia/churchflock/bin/rails:8:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/johncblandii/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by warrenbrown** [comment]
update in this issue?

**Comment by johncblandii** [comment]
Still not working for me on any project.

**Comment by samuelralak** [comment]
I am also having the same issue. any update on this?

**Comment by johncblandii** [comment]
Works for us on the latest build. We had to target master.

**Comment by graysonwright** [comment]
@johncblandii can you test it out with `0.1.4`? I just released that today, hopefully it includes the fix.

**Comment by johncblandii** [comment]
I think the above error may be resolved, but it still doesn't install for this project. Once I deleted ActiveAdmin, which conflicted pretty tough, everything installed as expected.

Here is the error I did see with ActiveAdmin still in place. There were a few others as I kept removing more and more of ActiveAdmin.
```
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/dashboard_dashboard.rb
/Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `const_get': uninitialized constant Dashboard (NameError)
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:107:in `klass'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
	from (erb):11:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `render'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block (2 levels) in invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `open'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:62:in `block in invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `call'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/empty_directory.rb:116:in `invoke_with_conflict_check'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:60:in `invoke!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:25:in `create_file'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:115:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:26:in `block in template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:60:in `inside_template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/generators/named_base.rb:25:in `template'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/dashboard/dashboard_generator.rb:30:in `create_dashboard_definition'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/administrate/generator_helpers.rb:4:in `call_generator'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:27:in `block in run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:26:in `run_dashboard_generators'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/generators.rb:157:in `invoke'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/johncblandii/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by mustiag** [comment]
@johncblandii...The error is most likely as a result of an issue with a has_many/through association in your models.  'administrate' scans all associations in your models, thus misconfiguration leads to this error. Hope this helps someone out there.

**Comment by johncblandii** [comment]
We've addressed it, thanks.

**Comment by carlosramireziii** [comment]
@warrenbrown I know it's been a while. Would you be able to tell if this is still an issue with the current version of Administrate? It seems as though others who are experiencing this have seen it be resolved. 

Let me know. Thanks!

**Comment by johncblandii** [comment]
@carlosramireziii, "we've addressed it" includes @warrenbrown. My fault for not clarifying. We were on the same project.

**Comment by carlosramireziii** [comment]
Got it! Thanks for letting me know. Glad you were able to address the issue 😀 Cheers!

**Comment by johncblandii** [comment]
Technically you guys did. :) It was a mix of an update to the lib and us cleaning up some of our stuff.

**Comment by echan00** [comment]
I'm still getting this error on v0.11.0

**Comment by dmc2015** [comment]
I am still getting this.

> The error is most likely as a result of an issue with a has_many/through association in your models. 'administrate' scans all associations in your models, thus misconfiguration leads to this error. Hope this helps someone out there.

Assuming this is accurate, I don't think this should be considered a misconfiguration if the models involved have no issues with CRUD functionality. In the very least it should communicate what the configuration is.
